# Header

menu:
  首页: /
  归档: /archives/
  分类: /categories
  关于: /about

logo: http://oe54phg1r.bkt.clouddn.com/blog/2017-07-26-075816.jpg

favicon: http://oe54phg1r.bkt.clouddn.com/favicon32x32.ico

# nav avatar
avatar: http://oe54phg1r.bkt.clouddn.com/blog/2017-07-26-075816.jpg